In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\Apoorv\Jupyter Notebooks\Campusx\Session\Week 12\smartphones - smartphones.csv")

In [3]:
data.head()

model    price  rating  \
0              OnePlus 11 5G  ₹54,999    89.0   
1  OnePlus Nord CE 2 Lite 5G  ₹19,989    81.0   
2      Samsung Galaxy A14 5G  ₹16,499    75.0   
3       Motorola Moto G62 5G  ₹14,999    81.0   
4         Realme 10 Pro Plus  ₹24,999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

While reviewing the data manually, several issues have been identified across various columns.

Let's categorize each column issues into two types: Quality Issues and Tidiness Issues.

1) <b>Quality Issues </b> refers to data points that is accurate in terms of information but is in the wrong format or stored in the wrong column.
2) <b>Tidiness Issues</b>, on the other hand, refers to data points that contains missing, inaccurate, or duplicate values.

Quality Issues can be further categorize into four aspects:

1) <b>Completeness</b>: Data that has missing values.
2) <b>Validity</b>: Data that is not valid, such as having negative values in columns for price or rating.
3) <b>Accuracy</b>: Data that is valid but contains inaccurate information, such as a feature phone being classified as a smartphone.
4) <b>Consistency</b>: Data that is written differently across different entries, such as Samsung being written as "Samsung", "SAMUNG", or "samsung".


### <b>Quality Issues<b>:<br>

model: some brands are written differently like OPPO in the model column (consistency)<br>
price: has unnecessary '₹' symbol (validity)<br>
price: has ',' between numbers (validity)<br>
price: phone Namotel has an unrealistic price of 99 (accuracy)<br>
ratings: missing values (completeness)<br>
processor: has some incorrect values for some Samsung phones (validity)<br>
memory: incorrect values in some rows (validity)<br>
battery: incorrect values in some rows (validity)<br>
display: sometimes frequency is not available (completeness)<br>
display: incorrect values in some rows (validity)<br>
information about foldable phones is scattered (validity)<br>
camera: words like Dual, Triple, and Quad are used to represent the number of cameras and front and rear cameras are separated by '&' (validity)<br>
camera: incorrect values in some rows (validity)<br>
card: sometimes contains information about the operating system and camera (validity)<br>
os: sometimes contains information about Bluetooth and FM radio (validity)<br>
os: incorrect values in some rows (validity)<br>
os: sometimes contains the version name of the operating system (consistency)<br>
missing values in camera, card, and os columns (completeness)<br>
incorrect data type of price and rating columns (validity)<br>
    
### <b>Tidiness Issues</b>:<br>

sim: can be split into three columns for 5G, NFC, and IR Blaster<br>
ram: can be split into two columns for RAM and ROM<br>
processor: can be split into columns for processor name, cores, and CPU speed<br>
battery: can be split into columns for battery capacity and fast charging availability<br>
display: can be split into columns for size, resolution width, resolution height, and frequency<br>
camera: can be split into columns for front and rear cameras<br>
card: can be split into columns for support and extended up to.

Before proceeding with any further steps, let's first convert the "price" column from string to integer to ensure that it can be processed properly.

In [4]:
data['price'] = data['price'].str.replace("₹","").str.replace(",","").astype('int')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   model      1020 non-null   object 
 1   price      1020 non-null   int32  
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object 
 4   processor  1020 non-null   object 
 5   ram        1020 non-null   object 
 6   battery    1020 non-null   object 
 7   display    1020 non-null   object 
 8   camera     1019 non-null   object 
 9   card       1013 non-null   object 
 10  os         1003 non-null   object 
dtypes: float64(1), int32(1), object(9)
memory usage: 83.8+ KB


Price column is convered to integer. It'll be easier for us to do analysis

In [6]:
data['price'].describe()

count      1020.000000
mean      31371.767647
std       39168.942590
min          99.000000
25%       12464.250000
50%       19815.000000
75%       34999.000000
max      650000.000000
Name: price, dtype: float64

It is apparent that both the minimum and maximum values in the data set are outliers. Further examination is required to determine their impact on the data.


Let's create a copy of our data before continuing with any additional steps.

In [7]:
df = data.copy()
df['Extra'] = 'Extra Details' 

To ensure that no information is lost, we will create an "Extra" column to temporarily store certain values. This column will be removed at the end of our processing.

Initially, we will examine the prices of phones that fall below 4000, as it is unlikely for a smartphone to have a price below that threshold.

In [8]:
df[df['price']<4000]

model  price  rating  \
190                      Realme C2s   3499    63.0   
400                  Jio JioPhone 2   2999     NaN   
473                    Nokia 110 4G   1762     NaN   
478                     Lyf Earth 1   3990    60.0   
532   Samsung Guru Music 2 Dual Sim   1949     NaN   
533                 Itel MagicX Pro   2799     NaN   
551                 itel Magic 2 4G   2399     NaN   
573                Nokia 105 (2019)   1299     NaN   
575                        Lyf C459   1999     NaN   
582                   Nokia 8210 4G   3749     NaN   
608               Namotel Achhe Din     99     NaN   
611                 Eunity U1 5605N    699     NaN   
627                    Nokia 225 4G   3589     NaN   
640                  Nokia 105 Plus   1299     NaN   
647               Motorola Moto A10   1339     NaN   
657                   Zanco Tiny T1   2799     NaN   
665                    itel it2163S    958     NaN   
685                    Xiaomi Qin 1   1799     NaN   
699           Samsung Guru GT-E1215   1850     NaN   
748                    Nokia 400 4G   3290     NaN   
757                    Karbonn KU3i    995     NaN   
817                    itel Magic X   2239     NaN   
835                  Eunity U1 King    599     NaN   
846                   DIZO Star 500   1749     NaN   
852                    Nokia 215 4G   3099     NaN   
873              BlackZone Ultra 4G   1899     NaN   
881                Nokia 110 (2022)   1599     NaN   
907                    Itel A23 Pro   3999     NaN   
917                Nokia 150 (2020)   2499     NaN   
925                   Nokia 3310 4G   3999     NaN   
926                     Lyf Earth 2   3890     NaN   
927              Samsung Guru E1200   1685     NaN   
930                iKall K88 Pro 4G   2099     NaN   
932                  Eunity U1 Livo    649     NaN   
988             Nokia 5310 Dual Sim   3399     NaN   
1000                XTouch F40 Flip   1999     NaN   

                                 sim  \
190   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
400   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
473          Dual Sim, 3G, 4G, VoLTE   
478   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
532                         Dual Sim   
533   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
551   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
573                       Single Sim   
575   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
582                 Dual Sim, 3G, 4G   
608              Dual Sim, 3G, Wi-Fi   
611                         Dual Sim   
627          Dual Sim, 3G, 4G, VoLTE   
640                         Dual Sim   
647                         Dual Sim   
657                       Single Sim   
665                         Dual Sim   
685                  Dual Sim, Wi-Fi   
699                       Single Sim   
748       Dual Sim, 4G, VoLTE, Wi-Fi   
757                         Dual Sim   
817   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
835                         Dual Sim   
846                         Dual Sim   
852          Dual Sim, 3G, 4G, VoLTE   
873          Dual Sim, 3G, 4G, VoLTE   
881                         Dual Sim   
907          Dual Sim, 3G, 4G, Wi-Fi   
917                         Dual Sim   
925   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
926   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
927                       Single Sim   
930          Dual Sim, 3G, 4G, VoLTE   
932                         Dual Sim   
988                         Dual Sim   
1000                        Dual Sim   

                                              processor  \
190             Helio  P22 , Octa Core, 2 GHz Processor   
400                          Dual Core, 1 GHz Processor   
473                                             No Wifi   
478        Snapdragon 615, Octa Core, 1.5 GHz Processor   
532                                             No Wifi   
533                                     1 GHz Processor   
551                                               No 3G   
573                                             No Wifi   
575    Snapdragon M

Since there are a few smartphones with prices below 4000, let's repeat the examination for prices below 3400.

In [9]:
df[df['price']<3400]

model  price  rating  \
400                  Jio JioPhone 2   2999     NaN   
473                    Nokia 110 4G   1762     NaN   
532   Samsung Guru Music 2 Dual Sim   1949     NaN   
533                 Itel MagicX Pro   2799     NaN   
551                 itel Magic 2 4G   2399     NaN   
573                Nokia 105 (2019)   1299     NaN   
575                        Lyf C459   1999     NaN   
608               Namotel Achhe Din     99     NaN   
611                 Eunity U1 5605N    699     NaN   
640                  Nokia 105 Plus   1299     NaN   
647               Motorola Moto A10   1339     NaN   
657                   Zanco Tiny T1   2799     NaN   
665                    itel it2163S    958     NaN   
685                    Xiaomi Qin 1   1799     NaN   
699           Samsung Guru GT-E1215   1850     NaN   
748                    Nokia 400 4G   3290     NaN   
757                    Karbonn KU3i    995     NaN   
817                    itel Magic X   2239     NaN   
835                  Eunity U1 King    599     NaN   
846                   DIZO Star 500   1749     NaN   
852                    Nokia 215 4G   3099     NaN   
873              BlackZone Ultra 4G   1899     NaN   
881                Nokia 110 (2022)   1599     NaN   
917                Nokia 150 (2020)   2499     NaN   
927              Samsung Guru E1200   1685     NaN   
930                iKall K88 Pro 4G   2099     NaN   
932                  Eunity U1 Livo    649     NaN   
988             Nokia 5310 Dual Sim   3399     NaN   
1000                XTouch F40 Flip   1999     NaN   

                                 sim  \
400   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
473          Dual Sim, 3G, 4G, VoLTE   
532                         Dual Sim   
533   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
551   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
573                       Single Sim   
575   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
608              Dual Sim, 3G, Wi-Fi   
611                         Dual Sim   
640                         Dual Sim   
647                         Dual Sim   
657                       Single Sim   
665                         Dual Sim   
685                  Dual Sim, Wi-Fi   
699                       Single Sim   
748       Dual Sim, 4G, VoLTE, Wi-Fi   
757                         Dual Sim   
817   Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
835                         Dual Sim   
846                         Dual Sim   
852          Dual Sim, 3G, 4G, VoLTE   
873          Dual Sim, 3G, 4G, VoLTE   
881                         Dual Sim   
917                         Dual Sim   
927                       Single Sim   
930          Dual Sim, 3G, 4G, VoLTE   
932                         Dual Sim   
988                         Dual Sim   
1000                        Dual Sim   

                                             processor  \
400                         Dual Core, 1 GHz Processor   
473                                            No Wifi   
532                                            No Wifi   
533                                    1 GHz Processor   
551                                              No 3G   
573                                            No Wifi   
575   Snapdragon MSM8909, Quad Core, 1.1 GHz Processor   
608                             1 GB RAM, 4 GB inbuilt   
611                                              No 3G   
640                             4 MB RAM, 4 MB inbuilt   
647                             4 MB RAM, 4 MB inbuilt   
657                           32 MB RAM, 32 MB inbuilt   
665                             4 MB RAM, 4 MB inbuilt   
685                                      Helio MT6260A   
699                                    800 mAh Battery   
748                                   2000 mAh Battery   
757                           52 MB RAM, 32 MB inbuilt   
817                                              No 3G   
835                                 1.77 MHz Processor   
846                          SC6531E, 26 MHz Pro

We will remove phones with prices below 3400 from our data set as the majority of these phones are likely feature phones rather than smartphones.

Additionally, we need to remove one iPod from our data set as it is not considered a smartphone.

In [551]:
df = df[df['price']>=3400]  
df.drop(754,axis = 0, inplace=True)

In [12]:
pd.set_option('display.max_rows', None)
df['processor'].value_counts()

Dimensity 700 5G, Octa Core, 2.2 GHz Processor         29
Helio P35, Octa Core, 2.3 GHz Processor                27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor       26
Snapdragon 695, Octa Core, 2.2 GHz Processor           23
Snapdragon 680, Octa Core, 2.4 GHz Processor           23
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor        23
Helio G35, Octa Core, 2.3 GHz Processor                20
Snapdragon  680, Octa Core, 2.4 GHz Processor          18
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor         18
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor          17
Bionic A15, Hexa Core, 3.22 GHz Processor              16
Snapdragon  695, Octa Core, 2.2 GHz Processor          16
Dimensity  810 5G, Octa Core, 2.4 GHz Processor        15
Snapdragon 870, Octa Core, 3.2 GHz Processor           15
Helio G80, Octa Core, 2 GHz Processor                  14
Helio G99, Octa Core, 2.2 GHz Processor                14
Snapdragon 778G, Octa Core, 2.4 GHz Processor          12
Helio G96, Oct

In [13]:
pd.set_option('display.max_rows', 10)

We are listing the common processors found in the data set.

In [14]:
df[~df['processor'].str.contains("Processor|Bionic|Apple|Snapdragon")] 

model  price  rating                             sim  \
376         Nokia 2660 Flip   4649     NaN                Dual Sim, 3G, 4G   
582           Nokia 8210 4G   3749     NaN                Dual Sim, 3G, 4G   
627            Nokia 225 4G   3589     NaN         Dual Sim, 3G, 4G, VoLTE   
645         Nokia 2760 Flip   5490     NaN         Dual Sim, 3G, 4G, Wi-Fi   
857             LG Folder 2  11999     NaN       Single Sim, 3G, 4G, Wi-Fi   
882  Nokia 5710 XpressAudio   4799     NaN                Dual Sim, 3G, 4G   
925           Nokia 3310 4G   3999     NaN  Dual Sim, 3G, 4G, VoLTE, Wi-Fi   

                      processor                               ram  \
376                     No Wifi                       Unisoc T107   
582                     No Wifi                       Unisoc T107   
627                 Unisoc T117         64 MB RAM, 128 MB inbuilt   
645            1450 mAh Battery  3.6 inches, 240 x 320 px Display   
857      1 GB RAM, 8 GB inbuilt                  1470 mAh Battery   
882                     No Wifi                       Unisoc T107   
925  256 MB RAM, 512 MB inbuilt                  1200 mAh Battery   

                              battery                            display  \
376         48 MB RAM, 128 MB inbuilt                   1450 mAh Battery   
582         48 MB RAM, 128 MB inbuilt                   1450 mAh Battery   
627                  1150 mAh Battery   2.4 inches, 240 x 320 px Display   
645     5 MP Rear & 5 MP Front Camera  Memory Card Supported, upto 32 GB   
857  2.8 inches, 240 x 320 px Display                   2 MP Rear Camera   
882         48 MB RAM, 128 MB inbuilt                   1450 mAh Battery   
925  2.4 inches, 240 x 320 px Display                   2 MP Rear Camera   

                                camera                               card  \
376   2.8 inches, 240 x 320 px Display                       Dual Display   
582   2.8 inches, 240 x 320 px Display                 0.3 MP Rear Camera   
627                 0.3 MP Rear Camera  Memory Card Supported, upto 32 GB   
645                         Kaios v3.0                          Bluetooth   
857              Memory Card Supported                          Bluetooth   
882   2.4 inches, 240 x 320 px Display                 0.3 MP Rear Camera   
925  Memory Card Supported, upto 32 GB                          Bluetooth   

                                    os          Extra  
376                 0.3 MP Rear Camera  Extra Details  
582  Memory Card Supported, upto 32 GB  Extra Details  
627                  RTOS (Series 30+)  Extra Details  
645                                NaN  Extra Details  
857                                NaN  Extra Details  
882  Memory Card Supported, upto 32 GB  Extra Details  
925                            Browser  Extra Details

None of the phones in this category are considered smartphones. They are all feature phones and fall outside the scope of our analysis. Therefore, we will remove them from the data set.

In [15]:
df.drop(df[~df['processor'].str.contains("Processor|Bionic|Apple|Snapdragon")].index,axis = 0, inplace = True)

We are converting all values to lower case to maintain consistency throughout the data set.

In [16]:
df.model = df.model.str.strip().str.lower()

In [17]:
df[~df['ram'].str.contains('RAM')] 

model   price  rating  \
439            apple iphone se 3 2022   43900     NaN   
483  huawei mate 50 rs porsche design  239999    81.0   
762                 apple iphone se 4   49990    60.0   

                                                 sim  \
439          Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
483  Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster   
762          Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                            processor             ram  \
439        Bionic  A15, Hexa Core, 3.22 GHz Processor   64 GB inbuilt   
483  Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor  512 GB inbuilt   
762        Bionic  A15, Hexa Core, 3.22 GHz Processor   64 GB inbuilt   

                                     battery  \
439        4.7 inches, 750 x 1334 px Display   
483  4700 mAh Battery with 66W Fast Charging   
762        6.1 inches, 750 x 1580 px Display   

                                         display  \
439               12 MP Rear & 7 MP Front Camera   
483  6.74 inches, 1212 x 2616 px, 120 Hz Display   
762            12 MP Rear & 10.8 MP Front Camera   

                                                camera  \
439                          Memory Card Not Supported   
483  50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...   
762                          Memory Card Not Supported   

                                  card                os          Extra  
439                            iOS v15       No FM Radio  Extra Details  
483  Memory Card (Hybrid), upto 256 GB  Hongmeng OS v3.0  Extra Details  
762                            iOS v16       No FM Radio  Extra Details

The "RAM" column has additional storage details that we will address later. Currently, our focus is solely on the values in this column.

In [18]:
df[df['battery'].isnull()]

Empty DataFrame
Columns: [model, price, rating, sim, processor, ram, battery, display, camera, card, os, Extra]
Index: []

We are shifting values from all the columns starting from "display" columns to ensure that all relevant information is captured and stored correctly.

In [19]:
df.loc[~df.battery.str.contains('mAh'), df.columns[6:]] = df[~df.battery.str.contains('mAh')].iloc[:,6:].shift(1,axis = 1)

With the above actions, we have corrected inaccurate values in most of the columns. To ensure the accuracy of the data, we will perform a thorough examination of each and every column.

In [20]:
df['battery'].fillna('Not Available', inplace = True)

It is only the Apple phones that do not have battery details in the data set.

In [21]:
df[~df['display'].str.contains('inch')]

Empty DataFrame
Columns: [model, price, rating, sim, processor, ram, battery, display, camera, card, os, Extra]
Index: []

In [22]:
df[~df['camera'].str.contains('MP')]

model   price  rating  \
69                            oppo find n fold   99990     NaN   
98                              vivo x fold 5g  106990     NaN   
155                            nokia 2780 flip    4990     NaN   
159                            oppo find n2 5g   94990     NaN   
236                       xiaomi mix fold 2 5g  106990     NaN   
...                                        ...     ...     ...   
894                        royole flexpai 3 5g  149999    87.0   
943   samsung galaxy z fold 4 (12gb ram + 1tb)  163980     NaN   
954          vivo x fold 5g (12gb ram + 512gb)  118990     NaN   
993                              huawei mate x  169000     NaN   
1014                             vivo x fold 2  119990     NaN   

                                                    sim  \
69              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
155                             Dual Sim, 3G, 4G, Wi-Fi   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
...                                                 ...   
894                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
943             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
954             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1014            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                              processor  \
69    Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
98        Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
155      Snapdragon QM215, Quad Core, 1.3 GHz Processor   
159    Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
236   Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Proce...   
...                                                 ...   
894       Snapdragon 888, Octa Core, 2.84 GHz Processor   
943   Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
954       Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
993           Kirin  990, Octa Core, 2.86 GHz Processor   
1014    Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   

                            ram                                  battery  \
69     8 GB RAM, 256 GB inbuilt  5000 mAh Battery with 67W Fast Charging   
98    12 GB RAM, 256 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
155    4 GB RAM, 512 MB inbuilt                         1450 mAh Battery   
159   12 GB RAM, 256 GB inbuilt  4520 mAh Battery with 67W Fast Charging   
236   12 GB RAM, 256 GB inbuilt  4500 mAh Battery with 67W Fast Charging   
...                         ...                                      ...   
894    8 GB RAM, 128 GB inbuilt                         3360 mAh Battery   
943     12 GB RAM, 1 TB inbuilt  4400 mAh Battery with 25W Fast Charging   
954   12 GB RAM, 512 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
993    8 GB RAM, 512 GB inbuilt  4500 mAh Battery with 55W Fast Charging   
1014  12 GB RAM, 256 GB inbuilt  4800 mAh Battery with 66W Fast Charging   

                                                display  \
69    7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
98          8.03 inches, 1916 x 2160 px, 120 Hz Display   
155                    2.7 inches, 240 x 320 px Display   
159   7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
236   8.02 inches, 1914 x 2160 px, 120 Hz Display wi...   
...                                                 ...   
894                  7.2 inches, 1440 x 1920 px Display   
943   7.6 inches, 1812 x 2176 px, 120 Hz Display wit...   
954         8.03 inches, 1916 x 2160 px, 120 Hz Display   
993                    8 inches, 2200 x 2480 px Display   
1014        8.03 inches, 1916 x 2160 px, 120 Hz Display   

                              camera  \
69    Foldable Display, Dual Display   
98                  Foldable Display   
155                     Dual Display   
159   Foldable Display, Dual Display   
236   Fo

The "Camera" column has information about the display type for a few phones. To accurately capture this information, we will create a separate column for it. For phones without any information in this column, we will use the value "Single Display".

In [23]:
display_type = df['camera']

In [24]:
display_type= display_type.reset_index()

We will write a function to convert missing values in the "Camera" column to "Single Display" where the display type is not specified.

In [25]:
def check(x):
    if "Display" in x:
        return x
    else:
        return "Normal Display"

In [26]:
display_type['camera'] = display_type['camera'].apply(check)

In [27]:
display_type = display_type.set_index('index')
display_type = display_type.squeeze() #We are converting the data back to a pandas series.

We will insert the newly created "display type" column into the 8th position in the data set.

In [28]:
df.insert(8,'display_type',display_type) 

In [29]:
df[~df['camera'].str.contains('MP')]

model   price  rating  \
69                            oppo find n fold   99990     NaN   
98                              vivo x fold 5g  106990     NaN   
155                            nokia 2780 flip    4990     NaN   
159                            oppo find n2 5g   94990     NaN   
236                       xiaomi mix fold 2 5g  106990     NaN   
...                                        ...     ...     ...   
894                        royole flexpai 3 5g  149999    87.0   
943   samsung galaxy z fold 4 (12gb ram + 1tb)  163980     NaN   
954          vivo x fold 5g (12gb ram + 512gb)  118990     NaN   
993                              huawei mate x  169000     NaN   
1014                             vivo x fold 2  119990     NaN   

                                                    sim  \
69              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
155                             Dual Sim, 3G, 4G, Wi-Fi   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
...                                                 ...   
894                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
943             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
954             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1014            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                              processor  \
69    Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
98        Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
155      Snapdragon QM215, Quad Core, 1.3 GHz Processor   
159    Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
236   Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Proce...   
...                                                 ...   
894       Snapdragon 888, Octa Core, 2.84 GHz Processor   
943   Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
954       Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
993           Kirin  990, Octa Core, 2.86 GHz Processor   
1014    Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   

                            ram                                  battery  \
69     8 GB RAM, 256 GB inbuilt  5000 mAh Battery with 67W Fast Charging   
98    12 GB RAM, 256 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
155    4 GB RAM, 512 MB inbuilt                         1450 mAh Battery   
159   12 GB RAM, 256 GB inbuilt  4520 mAh Battery with 67W Fast Charging   
236   12 GB RAM, 256 GB inbuilt  4500 mAh Battery with 67W Fast Charging   
...                         ...                                      ...   
894    8 GB RAM, 128 GB inbuilt                         3360 mAh Battery   
943     12 GB RAM, 1 TB inbuilt  4400 mAh Battery with 25W Fast Charging   
954   12 GB RAM, 512 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
993    8 GB RAM, 512 GB inbuilt  4500 mAh Battery with 55W Fast Charging   
1014  12 GB RAM, 256 GB inbuilt  4800 mAh Battery with 66W Fast Charging   

                                                display  \
69    7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
98          8.03 inches, 1916 x 2160 px, 120 Hz Display   
155                    2.7 inches, 240 x 320 px Display   
159   7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
236   8.02 inches, 1914 x 2160 px, 120 Hz Display wi...   
...                                                 ...   
894                  7.2 inches, 1440 x 1920 px Display   
943   7.6 inches, 1812 x 2176 px, 120 Hz Display wit...   
954         8.03 inches, 1916 x 2160 px, 120 Hz Display   
993                    8 inches, 2200 x 2480 px Display   
1014        8.03 inches, 1916 x 2160 px, 120 Hz Display   

                        display_type                          camera  \
69    Foldable Display, Dual Display  Foldable Display, Dual Display   
98                  Foldable Display                Foldable Dis

now camera column which have incorrect values needs to be shifted by 1. 

In [30]:
df[~df['camera'].str.contains('MP')]

model   price  rating  \
69                            oppo find n fold   99990     NaN   
98                              vivo x fold 5g  106990     NaN   
155                            nokia 2780 flip    4990     NaN   
159                            oppo find n2 5g   94990     NaN   
236                       xiaomi mix fold 2 5g  106990     NaN   
...                                        ...     ...     ...   
894                        royole flexpai 3 5g  149999    87.0   
943   samsung galaxy z fold 4 (12gb ram + 1tb)  163980     NaN   
954          vivo x fold 5g (12gb ram + 512gb)  118990     NaN   
993                              huawei mate x  169000     NaN   
1014                             vivo x fold 2  119990     NaN   

                                                    sim  \
69              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
155                             Dual Sim, 3G, 4G, Wi-Fi   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
...                                                 ...   
894                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
943             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
954             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1014            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                              processor  \
69    Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
98        Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
155      Snapdragon QM215, Quad Core, 1.3 GHz Processor   
159    Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
236   Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Proce...   
...                                                 ...   
894       Snapdragon 888, Octa Core, 2.84 GHz Processor   
943   Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
954       Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
993           Kirin  990, Octa Core, 2.86 GHz Processor   
1014    Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   

                            ram                                  battery  \
69     8 GB RAM, 256 GB inbuilt  5000 mAh Battery with 67W Fast Charging   
98    12 GB RAM, 256 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
155    4 GB RAM, 512 MB inbuilt                         1450 mAh Battery   
159   12 GB RAM, 256 GB inbuilt  4520 mAh Battery with 67W Fast Charging   
236   12 GB RAM, 256 GB inbuilt  4500 mAh Battery with 67W Fast Charging   
...                         ...                                      ...   
894    8 GB RAM, 128 GB inbuilt                         3360 mAh Battery   
943     12 GB RAM, 1 TB inbuilt  4400 mAh Battery with 25W Fast Charging   
954   12 GB RAM, 512 GB inbuilt  4600 mAh Battery with 66W Fast Charging   
993    8 GB RAM, 512 GB inbuilt  4500 mAh Battery with 55W Fast Charging   
1014  12 GB RAM, 256 GB inbuilt  4800 mAh Battery with 66W Fast Charging   

                                                display  \
69    7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
98          8.03 inches, 1916 x 2160 px, 120 Hz Display   
155                    2.7 inches, 240 x 320 px Display   
159   7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
236   8.02 inches, 1914 x 2160 px, 120 Hz Display wi...   
...                                                 ...   
894                  7.2 inches, 1440 x 1920 px Display   
943   7.6 inches, 1812 x 2176 px, 120 Hz Display wit...   
954         8.03 inches, 1916 x 2160 px, 120 Hz Display   
993                    8 inches, 2200 x 2480 px Display   
1014        8.03 inches, 1916 x 2160 px, 120 Hz Display   

                        display_type                          camera  \
69    Foldable Display, Dual Display  Foldable Display, Dual Display   
98                  Foldable Display                Foldable Dis

In [31]:
df.loc[~df['camera'].str.contains('MP'),df.columns[9]] = df.loc[~df['camera'].str.contains('MP'),df.columns[10]]

With the above actions, the "Camera" column no longer contains incorrect values.

In [32]:
df[~df['card'].str.contains("Memory")]

model   price  rating  \
8                 nothing phone 1   26749    85.0   
9              oneplus nord 2t 5g   28999    84.0   
12    xiaomi redmi note 12 pro 5g   24762    79.0   
17           oppo reno 9 pro plus   45999    86.0   
18                 oneplus 10r 5g   32999    86.0   
...                           ...     ...     ...   
1011                 oppo find x6   69990    89.0   
1012                    itel a23s    4787     NaN   
1013           google pixel 8 pro   70990    80.0   
1014                vivo x fold 2  119990     NaN   
1015   motorola moto edge s30 pro   34990    83.0   

                                                 sim  \
8            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
9            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
12    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster   
17           Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
18           Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
...                                              ...   
1011         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1012                         Dual Sim, 3G, 4G, Wi-Fi   
1013         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1014         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1015              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                              processor  \
8     Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...   
9           Dimensity  1300, Octa Core, 3 GHz Processor   
12         Dimensity 1080, Octa Core, 2.6 GHz Processor   
17     Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
18    Dimensity 8100 Max, Octa Core, 2.85 GHz Processor   
...                                                 ...   
1011    Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1012  Spreadtrum  SC9832E, Quad Core, 1.4 GHz Processor   
1013              Google  Tensor 3, Octa Core Processor   
1014    Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1015      Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   

                            ram                                    battery  \
8      8 GB RAM, 128 GB inbuilt    4500 mAh Battery with 33W Fast Charging   
9      8 GB RAM, 128 GB inbuilt    4500 mAh Battery with 80W Fast Charging   
12     6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
17    16 GB RAM, 256 GB inbuilt    4700 mAh Battery with 80W Fast Charging   
18     8 GB RAM, 128 GB inbuilt    5000 mAh Battery with 80W Fast Charging   
...                         ...                                        ...   
1011   8 GB RAM, 256 GB inbuilt   4700 mAh Battery with 120W Fast Charging   
1012    2 GB RAM, 32 GB inbuilt                           3020 mAh Battery   
1013  12 GB RAM, 256 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
1014  12 GB RAM, 256 GB inbuilt    4800 mAh Battery with 66W Fast Charging   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   

                                                display      display_type  \
8     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...    Normal Display   
9     6.43 inches, 1080 x 2400 px, 90 Hz Display wit...    Normal Display   
12    6.67 inches, 1080 x 2400 px, 120 Hz Display wi...    Normal Display   
17    6.7 inches, 1080 x 2412 px, 120 Hz Display wit...    Normal Display   
18    6.7 inches, 1080 x 2412 px, 120 Hz Display wit...    Normal Display   
...                                                 ...               ...   
1011  6.73 inches, 1080 x 2400 px, 120 Hz Display wi...    Normal Display   
1012                     5 inches, 854 x 480 px Display    Normal Display   
1013  6.73 inches, 1440 x 3120 px, 120 Hz Display wi...    Normal Display   
1014        8.03 inches, 1916 x 2160 px, 120 Hz Display  Foldable Display   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...    Normal Display   

                                                 camera  \
8          50 MP + 50 MP Dual Rear & 16 MP Front Camera   
9     50 MP + 8 MP + 2 MP Tri

There are 241 rows in the "card" column that contain incorrect values in the "memory card" information.

In [33]:
pd.set_option('display.max_rows', None)

In [34]:
df[~df['card'].str.contains("Memory")]['card'].value_counts()

Android v12                                                            107
Android v13                                                             46
Android v11                                                             41
Android v10                                                             11
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
Android v9.0 (Pie)                                                       2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
50 MP Quad Rear & 16 MP Front Camera                                     2
HarmonyOS v2.0                                                           1
iOS v13                                                                  1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
5 MP Rear & 2 MP Front Ca

handling camera details in card column

In [35]:
df[df['card'].str.contains('MP')]

model   price  rating  \
69                            oppo find n fold   99990     NaN   
98                              vivo x fold 5g  106990     NaN   
155                            nokia 2780 flip    4990     NaN   
159                            oppo find n2 5g   94990     NaN   
236                       xiaomi mix fold 2 5g  106990     NaN   
271                          nokia 2720 v flip    6199     NaN   
306                    samsung galaxy z flip 3   69999    84.0   
321                    samsung galaxy z fold 4  154998     NaN   
322                           royole flexpai 2  109999    87.0   
365                           oppo find n flip   89990    88.0   
392                          oppo find n2 flip   70990    88.0   
482                           vivo x fold plus  113990     NaN   
504                 samsung galaxy z flip 4 5g   89999    88.0   
569                    samsung galaxy z fold 3  110999    89.0   
570                                 lg wing 5g   54999    89.0   
613                               oukitel wp21   22990    82.0   
682                               lg v60 thinq   79990     NaN   
703                             oppo find n 5g   92249     NaN   
709                                oppo x 2021  134999    86.0   
721                 asus rog phone 6d ultimate  107990     NaN   
726                           huawei mate xs 2  162990    89.0   
790                         xiaomi mi mix fold  109990     NaN   
844                               cat s22 flip   14999     NaN   
894                        royole flexpai 3 5g  149999    87.0   
943   samsung galaxy z fold 4 (12gb ram + 1tb)  163980     NaN   
954          vivo x fold 5g (12gb ram + 512gb)  118990     NaN   
993                              huawei mate x  169000     NaN   
1014                             vivo x fold 2  119990     NaN   

                                                    sim  \
69              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
155                             Dual Sim, 3G, 4G, Wi-Fi   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
271                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
306           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
321             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
322                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
365           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
392           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
482             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
504             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
569             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
570             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
613                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
682             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
703             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
709                    Single Sim, 3G, 4G, VoLTE, Wi-Fi   
721             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
726     Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster   
790   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
844                    Single Sim, 3G, 4G, VoLTE, Wi-Fi   
894                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
943             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
954             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1014            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                              processor  \
69    Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor   
98        Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
155      Snapdragon QM215, Quad Core, 1.3 GHz Processor   
159    Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
236   Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Proce...   
271       Snapdragon 205 , Dual Core, 1.1 GHz Processor   
3

We will correct the "card" column by taking the memory card information from the "os" column and updating the values in the "card" column.

In [36]:
df.loc[df['os'].str.contains('Memory'), df.columns[10]] = df.loc[df['os'].str.contains('Memory'), df.columns[11]]

For the rows in the "card" column with incorrect values, we will update them to "Not available".

In [37]:
df.loc[~df['card'].str.contains("Memory|Android|OS"), df.columns[10]] = "Not Available"

In [38]:
df.loc[~df['card'].str.contains("Memory|Available"),df.columns[11]] = df.loc[~df['card'].str.contains("Memory|Available"),df.columns[10]]

In [39]:
df.loc[~df['card'].str.contains("Memory|Available"),df.columns[10]] = "Not Available"

In [40]:
df.loc[~df['os'].str.contains("Android|OS|Harmony|EMUI"), df.columns[11]] = "Not Available"

Now that we have corrected most of the inaccuracies in the data, let's examine the "Not available" values and see if we can fill them in.

We know that column "battery","os" and "card" have "Not Available" Values. Let's examine each of these columns for "Not Available" values and try to fill them in.

In [41]:
df[df['card'].str.contains('Available')]

model   price  rating  \
8                                    nothing phone 1   26749    85.0   
9                                 oneplus nord 2t 5g   28999    84.0   
12                       xiaomi redmi note 12 pro 5g   24762    79.0   
17                              oppo reno 9 pro plus   45999    86.0   
18                                    oneplus 10r 5g   32999    86.0   
20                                       oneplus 11r   39999    85.0   
21                                   vivo v25 pro 5g   35999    85.0   
24                                      vivo v26 pro   42990    87.0   
29                                    oneplus 11 pro   69999     NaN   
37                       samsung galaxy s22 ultra 5g   91999     NaN   
39                                    oppo reno 9 5g   28499    83.0   
51                                     iqoo neo 7 5g   29999    82.0   
58                           samsung galaxy s23 plus   84990    89.0   
60                       xiaomi redmi note 13 pro 5g   17990    78.0   
61                                          vivo s16   29990    85.0   
65                                      vivo s16 pro   35499    86.0   
66                                 oneplus 10 pro 5g   60999    89.0   
69                                  oppo find n fold   99990     NaN   
73                                       oneplus 10t   44999    85.0   
85                               motorola edge 30 5g   22999    83.0   
91                     oneplus ace racing edition 5g   22990    83.0   
93                              vivo x90 pro plus 5g   73999     NaN   
97                                        iqoo 11 5g   59999    88.0   
98                                    vivo x fold 5g  106990     NaN   
102                            motorola moto s30 pro   23990    83.0   
106                                     vivo v27 pro   43999    87.0   
107                            samsung galaxy s22 5g   49999    86.0   
109                oneplus 10r 5g (12gb ram + 256gb)   36999    87.0   
110                                 tecno phantom x2   39999    85.0   
112                             xiaomi redmi k50i 5g   22999    82.0   
115                                    oppo reno8 5g   29340    83.0   
119                               samsung galaxy s23   70990    88.0   
120                          motorola edge 30 pro 5g   34999    89.0   
121               oneplus nord 2t (12gb ram + 256gb)   33900    85.0   
133                nothing phone 1 (8gb ram + 256gb)   28249    86.0   
139                                    iqoo neo 6 5g   28999    82.0   
141                               oppo reno 9 pro 5g   39999    86.0   
146                                           iqoo 7   24990    83.0   
163                            oppo reno 10 pro plus   58990    88.0   
168                                     iqoo 9 se 5g   30990    83.0   
170                                      letv y1 pro    5499     NaN   
183                                motorola moto x40   39999    89.0   
186                                oneplus nord 3 5g   27999    84.0   
189                                     leeco s1 pro   10999    65.0   
196          oppo reno 8 pro house of dragon edition   45999    86.0   
202                           motorola edge 30 ultra   54999     NaN   
203                               xiaomi 13 ultra 5g   71999     NaN   
206               nothing phone 1 (12gb ram + 256gb)   35999    87.0   
209       xiaomi redmi note 12 pro (8gb ram + 256gb)   27994    82.0   
211                  vivo v25 pro (12gb ram + 256gb)   39999    86.0   
215                                        honor x9a   27999    81.0   
216                            google pixel 7 pro 5g   81999     NaN   
220                                 xiaomi redmi k60   29990    84.0   
223            motorola edge 30 5g (8gb ram + 128gb)   24999    85.0   
228                                 realme gt neo 3t   24999    79.0   
229            

It is best to remove the rows of feature phones in order to keep only the relevant data for our analysis of smartphones. Rows 155, 271, and 486 will be removed as they are not considered as smartphones.

In [42]:
df.drop([155,271,486],axis = 0, inplace=True)

In [43]:
df.head()

model  price  rating  \
0              oneplus 11 5g  54999    89.0   
1  oneplus nord ce 2 lite 5g  19989    81.0   
2      samsung galaxy a14 5g  16499    75.0   
3       motorola moto g62 5g  14999    81.0   
4         realme 10 pro plus  24999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os          Extra  
0         Memory Card Not Supported  Android v13  Extra Details  
1   Memory Card (Hybrid), upto 1 TB  Android v12  Extra Details  
2  Memory Card Supported, upto 1 TB  Android v13  Extra Details  
3   Memory Card (Hybrid), upto 1 TB  Android v12  Extra Details  
4         Memory Card Not Supported  Android v13  Extra Details

Let's examine the remaining values in the "Extra" column.

In [44]:
df[~df['Extra'].str.contains('Extra')]

model   price  rating  \
111               apple iphone 12   51999    74.0   
149          apple iphone 12 mini   40999    74.0   
307       apple iphone 12 (128gb)   55999    75.0   
363  apple iphone 12 mini (128gb)   45999    75.0   
439        apple iphone se 3 2022   43900     NaN   
448           apple iphone 15 pro  130990    75.0   
628   apple iphone 12 pro (512gb)  139900    80.0   
762             apple iphone se 4   49990    60.0   
853   apple iphone 12 pro (256gb)  119900    80.0   
913  apple iphone 12 mini (256gb)   55999    75.0   
914       apple iphone 12 (256gb)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

           battery                                            display  \
111  Not Available  6.1 inches, 1170 x 2532 px Display with Large ...   
149  Not Available                 5.4 inches, 1080 x 2340 px Display   
307  Not Available  6.1 inches, 1170 x 2532 px Display with Large ...   
363  Not Available                 5.4 inches, 1080 x 2340 px Display   
439  Not Available                  4.7 inches, 750 x 1334 px Display   
448  Not Available  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628  Not Available  6.1 inches, 1170 x 2532 px Display with Large ...   
762  Not Available                  6.1 inches, 750 x 1580 px Display   
853  Not Available  6.1 inches, 1170 x 2532 px Display with Large ...   
913  Not Available                 5.4 inches, 1080 x 2340 px Display   
914  Not Available  6.1 inches, 1170 x 2532 px Display with Large ...   

       display_type                                             camera  \
111  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439  Normal Display                     12 MP Rear & 7 MP Front Camera   
448  Normal Display  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628  Normal Display  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762  Normal Display                  12 MP Rear & 10.8 MP Front Camera   
853  Normal Display  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
913  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914  Normal Display       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                          card         os        Extra  
111  Memory Card Not Supported    iOS v14  No FM Radio  
149  Memo

Excellent, since there is no valuable information remaining in the "extra" column, we can safely remove it from our dataset.

In [45]:
df.drop(columns = ['Extra'],inplace = True)

Let's now save the corrected and cleaned data as a new table and proceed to the next step of feature engineering.

In [46]:
df.to_csv("smartprix_mobile_cleaned.csv", index = False)

# Data Cleaning

In [204]:
df = pd.read_csv("smartprix_mobile_cleaned.csv")

In [205]:
df.head()

model  price  rating  \
0              oneplus 11 5g  54999    89.0   
1  oneplus nord ce 2 lite 5g  19989    81.0   
2      samsung galaxy a14 5g  16499    75.0   
3       motorola moto g62 5g  14999    81.0   
4         realme 10 pro plus  24999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

Let's extract the mobile name and brand information from the 'model' column by splitting it into separate columns.

In [207]:
brand = df['model'].str.split(" ").str.get(0)
df.insert(0,"brand",brand)
df.head()

brand                      model  price  rating  \
0   oneplus              oneplus 11 5g  54999    89.0   
1   oneplus  oneplus nord ce 2 lite 5g  19989    81.0   
2   samsung      samsung galaxy a14 5g  16499    75.0   
3  motorola       motorola moto g62 5g  14999    81.0   
4    realme         realme 10 pro plus  24999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

In [208]:
df.model = df['model'].str.split(" ").str[1:].apply(lambda x: " ".join(x))

In [209]:
df.head()

brand              model  price  rating  \
0   oneplus              11 5g  54999    89.0   
1   oneplus  nord ce 2 lite 5g  19989    81.0   
2   samsung      galaxy a14 5g  16499    75.0   
3  motorola        moto g62 5g  14999    81.0   
4    realme        10 pro plus  24999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

Let's separate the values in the SIM column which include "Dual Sim," "3G," "4G," "5G," "VoLTE," "Wi-Fi," "NFC," and "IR Blaster."

In [210]:
df['sim'].value_counts()

Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               317
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                54
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, Wi-Fi                                        6
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi

Create a function that can extract the values from the SIM column and create the following columns:

1) Number of sims
2) 5G capability
3) VoLTE support
4) NFC compatibility
5) IR Blaster availability <p>
Note that most of the phones already have 3G, 4G, and Wi-Fi capabilities, so we will not create separate columns for those.

In [211]:

def check_values(x,y):
    if y in x:
        return "yes"
    else:
        return "no"

g5 = df['sim'].apply(lambda x: check_values(x, '5G'))
volte = df['sim'].apply(lambda x: check_values(x, 'VoLTE'))
nfc = df['sim'].apply(lambda x: check_values(x, 'NFC'))
ir_blaster = df['sim'].apply(lambda x: check_values(x, 'IR Blaster'))


In [212]:
def sim_type(x):
    if "Dual" in x:
        return "Dual Sim"
    else:
        return "Single Sim"
sim_type = df['sim'].apply(sim_type)

Let's add the newly created columns to the data frame and place them between the 5th and 9th position.

In [214]:
df.insert(5,'sim_type',sim_type)
df.insert(6,'5g',g5)
df.insert(7,'volte',volte)
df.insert(8,'nfc',nfc)
df.insert(9,'ir_blaster',ir_blaster)

In [215]:
df.head()

brand              model  price  rating  \
0   oneplus              11 5g  54999    89.0   
1   oneplus  nord ce 2 lite 5g  19989    81.0   
2   samsung      galaxy a14 5g  16499    75.0   
3  motorola        moto g62 5g  14999    81.0   
4    realme        10 pro plus  24999    82.0   

                                       sim  sim_type   5g volte  nfc  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC  Dual Sim  yes   yes  yes   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi  Dual Sim  yes   yes   no   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi  Dual Sim  yes   yes   no   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi  Dual Sim  yes   yes   no   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi  Dual Sim  yes   yes   no   

  ir_blaster                                        processor  \
0         no  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1         no     Snapdragon 695, Octa Core, 2.2 GHz Processor   
2         no        Exynos 1330, Octa Core, 2.4 GHz Processor   
3         no    Snapdragon  695, Octa Core, 2.2 GHz Processor   
4         no     Dimensity 1080, Octa Core, 2.6 GHz Processor   

                         ram                                   battery  \
0  12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   
1   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
2    4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 15W Fast Charging   
3   6 GB RAM, 128 GB inbuilt       5000 mAh Battery with Fast Charging   
4   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

With the new columns created from the "SIM" column, the information it contains has been extracted and is no longer necessary. Thus, the "SIM" column can now be removed.

In [216]:
df.drop('sim', axis = 1, inplace = True)

In [217]:
df.head()

brand              model  price  rating  sim_type   5g volte  nfc  \
0   oneplus              11 5g  54999    89.0  Dual Sim  yes   yes  yes   
1   oneplus  nord ce 2 lite 5g  19989    81.0  Dual Sim  yes   yes   no   
2   samsung      galaxy a14 5g  16499    75.0  Dual Sim  yes   yes   no   
3  motorola        moto g62 5g  14999    81.0  Dual Sim  yes   yes   no   
4    realme        10 pro plus  24999    82.0  Dual Sim  yes   yes   no   

  ir_blaster                                        processor  \
0         no  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1         no     Snapdragon 695, Octa Core, 2.2 GHz Processor   
2         no        Exynos 1330, Octa Core, 2.4 GHz Processor   
3         no    Snapdragon  695, Octa Core, 2.2 GHz Processor   
4         no     Dimensity 1080, Octa Core, 2.6 GHz Processor   

                         ram                                   battery  \
0  12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   
1   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
2    4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 15W Fast Charging   
3   6 GB RAM, 128 GB inbuilt       5000 mAh Battery with Fast Charging   
4   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

Let's examine the processor column to see if any valuable insights can be obtained from it.

Before exploring the data in the processor column, let's first clean it up by using the .strip method so that all processor names are in a consistent format.

In [218]:
df['processor'] = df['processor'].str.strip()

In [219]:
df['processor'].value_counts()

Dimensity 700 5G, Octa Core, 2.2 GHz Processor         29
Helio P35, Octa Core, 2.3 GHz Processor                27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor       26
Snapdragon 695, Octa Core, 2.2 GHz Processor           24
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor        23
Snapdragon 680, Octa Core, 2.4 GHz Processor           23
Helio G35, Octa Core, 2.3 GHz Processor                20
Snapdragon  695, Octa Core, 2.2 GHz Processor          19
Snapdragon  680, Octa Core, 2.4 GHz Processor          18
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor         18
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor          17
Bionic A15, Hexa Core, 3.22 GHz Processor              16
Dimensity  810 5G, Octa Core, 2.4 GHz Processor        15
Snapdragon 870, Octa Core, 3.2 GHz Processor           15
Helio G80, Octa Core, 2 GHz Processor                  14
Helio G99, Octa Core, 2.2 GHz Processor                14
Helio G96, Octa Core, 2.05 GHz Processor               12
Dimensity 1080

Let's split the processor column into three separate columns for brand, speed, and number of cores.

In [220]:
processor_name = df['processor'].str.split(',').str.get(0)
num_cores = df['processor'].str.split(',').str.get(1)
processor_speed = df['processor'].str.split(',').str.get(2)

Additionally, the newly created columns provide further insight into the phone's processing capabilities, which can be important to many users. These columns can be inserted at positions 10th to 12th within the data frame to provide a more comprehensive view of the data.

In [221]:
df.insert(10,'processor_name',processor_name)
df.insert(11,'num_cores',num_cores)
df.insert(12,'processor_speed',processor_speed)

In [222]:
df.head()

brand              model  price  rating  sim_type   5g volte  nfc  \
0   oneplus              11 5g  54999    89.0  Dual Sim  yes   yes  yes   
1   oneplus  nord ce 2 lite 5g  19989    81.0  Dual Sim  yes   yes   no   
2   samsung      galaxy a14 5g  16499    75.0  Dual Sim  yes   yes   no   
3  motorola        moto g62 5g  14999    81.0  Dual Sim  yes   yes   no   
4    realme        10 pro plus  24999    82.0  Dual Sim  yes   yes   no   

  ir_blaster                                        processor  \
0         no  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1         no     Snapdragon 695, Octa Core, 2.2 GHz Processor   
2         no        Exynos 1330, Octa Core, 2.4 GHz Processor   
3         no    Snapdragon  695, Octa Core, 2.2 GHz Processor   
4         no     Dimensity 1080, Octa Core, 2.6 GHz Processor   

      processor_name   num_cores     processor_speed  \
0  Snapdragon 8 Gen2   Octa Core   3.2 GHz Processor   
1     Snapdragon 695   Octa Core   2.2 GHz Processor   
2        Exynos 1330   Octa Core   2.4 GHz Processor   
3    Snapdragon  695   Octa Core   2.2 GHz Processor   
4     Dimensity 1080   Octa Core   2.6 GHz Processor   

                         ram                                   battery  \
0  12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   
1   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
2    4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 15W Fast Charging   
3   6 GB RAM, 128 GB inbuilt       5000 mAh Battery with Fast Charging   
4   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

The "processor" column can now be removed as all its information has been extracted and separated into the newly created columns "processor brand", "processor speed", and "number of cores".

In [223]:
df.drop('processor',axis =1, inplace = True) 

In [224]:
df['processor_name'].value_counts()

Dimensity 700 5G           29
Helio P35                  28
Snapdragon 8+ Gen1         26
Snapdragon 695             24
Snapdragon 8 Gen2          23
Snapdragon 680             23
Helio G35                  20
Snapdragon  695            19
Snapdragon  8 Gen1         18
Snapdragon  680            18
Snapdragon 8 Gen1          17
Bionic A15                 16
Helio G96                  15
Snapdragon 870             15
Dimensity  810 5G          15
Helio G80                  14
Helio G99                  14
Dimensity 810 5G           12
Snapdragon  8+ Gen1        12
Dimensity 1080             12
Snapdragon 778G            12
Snapdragon 888             11
Dimensity  920 5G          11
Helio G37                  11
Helio G95                  10
Helio G25                  10
Helio  G85                 10
Helio A22                  10
Bionic  A16                10
Snapdragon  888            10
Tiger T612                  9
Octa Core Processor         9
Bionic A14                  8
Snapdragon

Let's examine the entries in the "processor" column for instances of "octa core processor", which is an invalid value for this column

In [225]:
df[df['processor_name'].str.contains('Core')]

brand                         model  price  rating  sim_type   5g  \
118    tesla                      pi phone  69999    83.0  Dual Sim  yes   
143      jio                       phone 3   4499     NaN  Dual Sim   no   
187    ikall                       z19 pro   8099    60.0  Dual Sim   no   
200  samsung                    galaxy a13  14450    75.0  Dual Sim   no   
307  samsung  galaxy a13 (4gb ram + 128gb)  14999    75.0  Dual Sim   no   
313     itel                       s16 pro   6990     NaN  Dual Sim   no   
490  samsung                    galaxy a15  15990    63.0  Dual Sim   no   
523  samsung                    galaxy f14  14990    67.0  Dual Sim   no   
575  samsung  galaxy a13 (6gb ram + 128gb)  16499    78.0  Dual Sim   no   
733    ikall                           z19   7999    61.0  Dual Sim   no   
753    tecno                 spark go 2022   6249    61.0  Dual Sim   no   
769     itel                           a56   5490     NaN  Dual Sim   no   
799  samsung              galaxy s23 fe 5g  54999    77.0  Dual Sim  yes   
800  samsung                galaxy m51s 5g  24990    72.0  Dual Sim  yes   
844   huawei                      nova y61  21990    63.0  Dual Sim   no   
910  samsung                    galaxy m35  22999    74.0  Dual Sim   no   
911  samsung                    galaxy a05  12990    63.0  Dual Sim   no   
952  samsung                    galaxy a11   9990    63.0  Dual Sim   no   
965    ikall                           z18   6799    61.0  Dual Sim   no   
979  samsung                galaxy m52s 5g  24990    74.0  Dual Sim  yes   

    volte  nfc ir_blaster       processor_name           num_cores  \
118   yes  yes         no  Octa Core Processor                 NaN   
143   yes   no         no            Quad Core   1.4 GHz Processor   
187   yes   no         no            Quad Core   1.6 GHz Processor   
200   yes   no         no            Octa Core     2 GHz Processor   
307   yes   no         no            Octa Core     2 GHz Processor   
313   yes   no         no            Quad Core   1.3 GHz Processor   
490   yes   no         no  Octa Core Processor                 NaN   
523   yes  yes         no  Octa Core Processor                 NaN   
575   yes   no         no            Octa Core     2 GHz Processor   
733   yes   no         no            Quad Core   1.6 GHz Processor   
753   yes   no         no            Octa Core   2.2 GHz Processor   
769   yes   no         no            Quad Core   1.3 GHz Processor   
799   yes  yes         no  Octa Core Processor                 NaN   
800   yes   no         no  Octa Core Processor                 NaN   
844   yes   no         no  Octa Core Processor                 NaN   
910   yes  yes         no  Octa Core Processor                 NaN   
911   yes   no         no  Octa Core Processor                 NaN   
952   yes   no         no            Octa Core   1.8 GHz Processor   
965   yes   no         no            Quad Core   1.3 GHz Processor   
979   yes   no         no  Octa Core Processor                 NaN   

    processor_speed                        ram  \
118             NaN  16 GB RAM, 512 GB inbuilt   
143             NaN    2 GB RAM, 64 GB inbuilt   
187             NaN    4 GB RAM, 64 GB inbuilt   
200             NaN    4 GB RAM, 64 GB inbuilt   
307             NaN   4 GB RAM, 128 GB inbuilt   
313             NaN    2 GB RAM, 32 GB inbuilt   
490             NaN    6 GB RAM, 64 GB inbuilt   
523             NaN    4 GB RAM, 64 GB inbuilt   
575             NaN   6 GB RAM, 128 GB inbuilt   
733             NaN    4 GB RAM, 32 GB inbuilt   
753             NaN    2 GB RAM, 32 GB inbuilt   
769             NaN    1 GB RAM, 16 GB inbuilt   
799             NaN   8 GB RAM, 128 GB inbuilt   
800             NaN   6 GB RAM, 128 GB inbuilt   
844             NaN    4 GB RAM, 64 GB inbuilt   
910             NaN   8 GB RAM, 128 GB inbuilt   
911             NaN    4 GB RAM, 64 GB inbuilt   
952             NaN    2 GB RAM, 32 GB 

So, for these rows with incorrect processor names, it seems like the data has been shifted and the subsequent columns containing information about the processor speed and number of cores are empty.

In [226]:
df[df['processor_speed'].isnull()]

brand                         model   price  rating    sim_type   5g  \
27     apple             iphone 14 pro max  129990    76.0    Dual Sim  yes   
78   samsung                 galaxy a34 5g   24999    75.0    Dual Sim  yes   
100    apple                 iphone 14 pro  119990    75.0    Dual Sim  yes   
118    tesla                      pi phone   69999    83.0    Dual Sim  yes   
122   google                      pixel 6a   29999    71.0    Dual Sim  yes   
129   google                      pixel 7a   34990    69.0    Dual Sim  yes   
143      jio                       phone 3    4499     NaN    Dual Sim   no   
152    apple             iphone 15 pro max  142990    79.0    Dual Sim  yes   
187    ikall                       z19 pro    8099    60.0    Dual Sim   no   
200  samsung                    galaxy a13   14450    75.0    Dual Sim   no   
206  samsung                 galaxy a54 5g   34999    76.0    Dual Sim  yes   
209    apple     iphone 14 pro max (256gb)  139990    77.0    Dual Sim  yes   
224     vivo                           y02    8999     NaN    Dual Sim   no   
241  samsung                 galaxy a75 5g   44999    83.0    Dual Sim  yes   
255  samsung              galaxy s22 fe 5g   51999    79.0    Dual Sim  yes   
262    apple                    iphone xr2   71999    60.0    Dual Sim   no   
280    apple                iphone 14 mini   69990    70.0    Dual Sim   no   
288    apple       iphone 14 pro max (1tb)  182999    78.0    Dual Sim  yes   
307  samsung  galaxy a13 (4gb ram + 128gb)   14999    75.0    Dual Sim   no   
313     itel                       s16 pro    6990     NaN    Dual Sim   no   
362  samsung              galaxy s24 ultra  119990    85.0    Dual Sim  yes   
380     letv                        y2 pro    6999     NaN    Dual Sim   no   
398    apple               iphone 15 ultra  149900    79.0    Dual Sim  yes   
416    apple         iphone 14 pro (256gb)  129990    76.0    Dual Sim  yes   
425    nokia                        x50 5g   34999    76.0  Single Sim  yes   
444    apple                 iphone 15 pro  130990    75.0    Dual Sim  yes   
490  samsung                    galaxy a15   15990    63.0    Dual Sim   no   
523  samsung                    galaxy f14   14990    67.0    Dual Sim   no   
575  samsung  galaxy a13 (6gb ram + 128gb)   16499    78.0    Dual Sim   no   
640  oneplus                        nord 5   34999    76.0    Dual Sim  yes   
668     vivo          y02 (2gb ram + 32gb)    7999     NaN    Dual Sim   no   
706    apple                     iphone 15   82990    72.0    Dual Sim   no   
733    ikall                           z19    7999    61.0    Dual Sim   no   
735     vivo                       s17 pro   49990    77.0    Dual Sim  yes   
739    apple     iphone 14 pro max (512gb)  169900    78.0    Dual Sim  yes   
740   google                       pixel 8   53990    75.0    Dual Sim  yes   
753    tecno                 spark go 2022    6249    61.0    Dual Sim   no   
769     itel                           a56    5490     NaN    Dual Sim   no   
789    apple           iphone 14 pro (1tb)  172999    77.0    Dual Sim  yes   
799  samsung              galaxy s23 fe 5g   54999    77.0    Dual Sim  yes   
800  samsung                galaxy m51s 5g   24990    72.0    Dual Sim  yes   
802     poco                     x6 pro 5g   19999    72.0    Dual Sim  yes   
804  samsung                    galaxy m14   14999    60.0    Dual Sim   no   
805     vivo                     t2 pro 5g   29990    76.0    Dual Sim  yes   
844   huawei                      nova y61   21990    63.0    Dual Sim   no   
845     iqoo                            z9   19990    76.0    Dual Sim  yes   
892    apple                iphone 15 plus   84990    75.0    Dual Sim  yes   
910  samsung                    galaxy m35   22999    74.0    Dual Sim   no   
911  samsung                    galaxy a05   12990    63.0    Dual Sim   no   
952  samsung                    galaxy a11    9990    63.

Let's fill the missing values in the two columns with "Not available" so that we can perform string operations on them.

In [227]:
df['processor_speed'].fillna('Not Available',inplace=True)
df['num_cores'].fillna('Not Available',inplace=True)
df['processor_name'].fillna('Not Available',inplace=True)

In [228]:
df.loc[df['num_cores'].str.contains('G'),df.columns[11]] = df.loc[df['num_cores'].str.contains('G'),df.columns[10]]

In [229]:
df.loc[df['num_cores'].str.contains('G'),df.columns[10]] = "Not Available"

In [230]:
df.loc[df['processor_name'].str.contains('Core'),df.columns[10]] = df.loc[df['processor_name'].str.contains('Core'),df.columns[9]]

In [231]:
df.loc[df['processor_name'].str.contains('Core'),df.columns[9]] = "Not Available"

Okay, let's create a new column called "processor_brand" that will extract more information from the "processor" column and insert it into the 9th position in the data frame.

In [232]:
brand = df['processor_name'].str.split(" ").str.get(0).str.lower().str.strip()

In [233]:
df.insert(9,'processor_brand', brand)

In [234]:
df.loc[df['processor_brand'].str.contains("28|not"),df.columns[9]] = "Not Available"

In [235]:
df.head(1)

brand  model  price  rating  sim_type   5g volte  nfc ir_blaster  \
0  oneplus  11 5g  54999    89.0  Dual Sim  yes   yes  yes         no   

  processor_brand     processor_name   num_cores     processor_speed  \
0      snapdragon  Snapdragon 8 Gen2   Octa Core   3.2 GHz Processor   

                         ram                                   battery  \
0  12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   

                        card           os  
0  Memory Card Not Supported  Android v13

Now, let's remove the "processor" column as it will no longer be necessary.

In [236]:
df.drop('processor_name',axis = 1 , inplace = True) 

Let's check the num_cores column and see what insights we can get

In [237]:
df['num_cores'] = df['num_cores'].str.strip().str.lower()

For the "num_cores" column, the following operations are being performed:
<ul>
<li>Rows that contain the string "octa" are having the value in the 10th column set to 8.
<li>Rows that contain the string "quad" are having the value in the 10th column set to 4.
<li>Rows that contain the string "hexa" are having the value in the 10th column set to 6.
<li>Rows that contain the string "not" are having the value in the 10th column set to 0.</ul>

In [238]:
df.loc[df['num_cores'].str.contains('octa',na=False),df.columns[10]] = 8
df.loc[df['num_cores'].str.contains('quad',na=False),df.columns[10]] = 4
df.loc[df['num_cores'].str.contains('hexa',na=False),df.columns[10]] = 6
df.loc[df['num_cores'].str.contains('not',na=False),df.columns[10]] = 0

In [242]:
df['num_cores'].value_counts()

8    899
6     39
4     36
0      6
Name: num_cores, dtype: int64

#### Cleaning the Processor Speed Column

Splitting the values in the "processor_speed" column by the " " (space) character, and taking the second element in the resulting list

In [243]:
df['processor_speed'] = df['processor_speed'].str.split(" ").str.get(1)

Replacing the string "Available" with "Not Available" in the "processor_speed" column

In [244]:
df['processor_speed'] = df['processor_speed'].str.replace("Available","Not Available")

In [245]:
df['processor_speed'].value_counts()

2 GHz            146
2.2 GHz          135
2.4 GHz          128
3.2 GHz           94
2.3 GHz           86
3 GHz             53
Not Available     42
2.84 GHz          36
2.05 GHz          28
2.5 GHz           23
1.8 GHz           23
1.6 GHz           20
2.85 GHz          19
3.22 GHz          18
3.1 GHz           15
2.6 GHz           14
2.9 GHz           13
1.3 GHz           10
1.82 GHz          10
2.73 GHz           9
2.8 GHz            9
3.05 GHz           8
2.36 GHz           8
1.4 GHz            5
2.65 GHz           5
2.7 GHz            5
1.5 GHz            4
2.96 GHz           3
2.86 GHz           3
3.13 GHz           2
2.35 GHz           1
2.37 GHz           1
1.99 GHz           1
1.95 GHz           1
2.1 GHz            1
1.2 GHz            1
Name: processor_speed, dtype: int64

In [246]:
df['processor_speed'].str.split(" ")[0]

['3.2\u2009GHz']

Here, there is a "/u2009" between the numbers, so we will utilize it for splitting.

In [247]:
df['processor_speed'] = df['processor_speed'].str.split("\u2009").str.get(0)

Let's replace the value "Not Available" in the "RAM" column with 0 as there is no information available.

In [248]:
df.loc[df['processor_speed'].str.contains('Not'),df.columns[11]] = 0

Let's convert the "processor_speed" column from an object datatype to a float datatype, as it only contains numerical values.

In [249]:
df['processor_speed'] = df['processor_speed'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   brand            980 non-null    object 
 1   model            980 non-null    object 
 2   price            980 non-null    int64  
 3   rating           879 non-null    float64
 4   sim_type         980 non-null    object 
 5   5g               980 non-null    object 
 6   volte            980 non-null    object 
 7   nfc              980 non-null    object 
 8   ir_blaster       980 non-null    object 
 9   processor_brand  980 non-null    object 
 10  num_cores        980 non-null    object 
 11  processor_speed  980 non-null    float64
 12  ram              980 non-null    object 
 13  battery          980 non-null    object 
 14  display          980 non-null    object 
 15  display_type     980 non-null    object 
 16  camera           980 non-null    object 
 17  card            

In [250]:
df['ram']

0      12 GB RAM, 256 GB inbuilt
1       6 GB RAM, 128 GB inbuilt
2        4 GB RAM, 64 GB inbuilt
3       6 GB RAM, 128 GB inbuilt
4       6 GB RAM, 128 GB inbuilt
5       6 GB RAM, 128 GB inbuilt
6       6 GB RAM, 128 GB inbuilt
7       8 GB RAM, 256 GB inbuilt
8       8 GB RAM, 128 GB inbuilt
9       8 GB RAM, 128 GB inbuilt
10      6 GB RAM, 128 GB inbuilt
11      8 GB RAM, 128 GB inbuilt
12      6 GB RAM, 128 GB inbuilt
13      6 GB RAM, 128 GB inbuilt
14      8 GB RAM, 256 GB inbuilt
15      4 GB RAM, 128 GB inbuilt
16       3 GB RAM, 32 GB inbuilt
17     16 GB RAM, 256 GB inbuilt
18      8 GB RAM, 128 GB inbuilt
19       4 GB RAM, 64 GB inbuilt
20      8 GB RAM, 128 GB inbuilt
21      8 GB RAM, 128 GB inbuilt
22       6 GB RAM, 64 GB inbuilt
23      4 GB RAM, 128 GB inbuilt
24     12 GB RAM, 256 GB inbuilt
25      8 GB RAM, 128 GB inbuilt
26      8 GB RAM, 128 GB inbuilt
27      6 GB RAM, 128 GB inbuilt
28      8 GB RAM, 128 GB inbuilt
29      8 GB RAM, 128 GB inbuilt
30      8 

Let's create two columns from the "RAM" column: "RAM_storage" and "RAM_amount". This will allow us to better understand and analyze the data stored in the "RAM" column.

In [251]:
storage = df['ram'].str.split(',').str.get(1)

In [252]:
df.insert(13,'storage',storage)
df.head()

brand              model  price  rating  sim_type   5g volte  nfc  \
0   oneplus              11 5g  54999    89.0  Dual Sim  yes   yes  yes   
1   oneplus  nord ce 2 lite 5g  19989    81.0  Dual Sim  yes   yes   no   
2   samsung      galaxy a14 5g  16499    75.0  Dual Sim  yes   yes   no   
3  motorola        moto g62 5g  14999    81.0  Dual Sim  yes   yes   no   
4    realme        10 pro plus  24999    82.0  Dual Sim  yes   yes   no   

  ir_blaster processor_brand num_cores  processor_speed  \
0         no      snapdragon         8              3.2   
1         no      snapdragon         8              2.2   
2         no          exynos         8              2.4   
3         no      snapdragon         8              2.2   
4         no       dimensity         8              2.6   

                         ram          storage  \
0  12 GB RAM, 256 GB inbuilt   256 GB inbuilt   
1   6 GB RAM, 128 GB inbuilt   128 GB inbuilt   
2    4 GB RAM, 64 GB inbuilt    64 GB inbuilt   
3   6 GB RAM, 128 GB inbuilt   128 GB inbuilt   
4   6 GB RAM, 128 GB inbuilt   128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display    display_type  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...  Normal Display   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...  Normal Display   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...  Normal Display   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...  Normal Display   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...  Normal Display   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

In [253]:
df['ram'] = df['ram'].str.split(',').str.get(0)

In [254]:
df.ram.value_counts()

8 GB RAM          339
6 GB RAM          234
4 GB RAM          215
12 GB RAM          85
3 GB RAM           54
2 GB RAM           32
16 GB RAM           9
1 GB RAM            7
18 GB RAM           2
64 GB inbuilt       2
512 GB inbuilt      1
Name: ram, dtype: int64

In [255]:
df.storage.value_counts()

 128 GB inbuilt    523
 64 GB inbuilt     191
 256 GB inbuilt    157
 32 GB inbuilt      67
 512 GB inbuilt     21
 16 GB inbuilt      12
 1 TB inbuilt        5
 8 GB inbuilt        1
Name: storage, dtype: int64

In [256]:
df[df['ram'].str.contains('inbuilt')]

brand                      model   price  rating  sim_type   5g volte  \
435   apple           iphone se 3 2022   43900     NaN  Dual Sim  yes   yes   
478  huawei  mate 50 rs porsche design  239999    81.0  Dual Sim   no   yes   
737   apple                iphone se 4   49990    60.0  Dual Sim  yes   yes   

     nfc ir_blaster processor_brand num_cores  processor_speed  \
435  yes         no          bionic         6             3.22   
478  yes        yes      snapdragon         8             3.20   
737  yes         no          bionic         6             3.22   

                ram storage                                  battery  \
435   64 GB inbuilt     NaN                            Not Available   
478  512 GB inbuilt     NaN  4700 mAh Battery with 66W Fast Charging   
737   64 GB inbuilt     NaN                            Not Available   

                                         display    display_type  \
435            4.7 inches, 750 x 1334 px Display  Normal Display   
478  6.74 inches, 1212 x 2616 px, 120 Hz Display  Normal Display   
737            6.1 inches, 750 x 1580 px Display  Normal Display   

                                                camera  \
435                     12 MP Rear & 7 MP Front Camera   
478  50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...   
737                  12 MP Rear & 10.8 MP Front Camera   

                                  card                os  
435          Memory Card Not Supported           iOS v15  
478  Memory Card (Hybrid), upto 256 GB  Hongmeng OS v3.0  
737          Memory Card Not Supported           iOS v16

Let's manually fill the missing RAM details for phones in the data set by referring to the following examples:
<ul>
<li>Apple iPhone SE3 with 4 GB RAM
<li>Huawei Mate 50 with 12 GB RAM
<li>Apple iPhone SE4 with 4 GB RAM
</ul>

In [257]:
df.iloc[762,13]

' 32\u2009GB inbuilt'

Let's reset the index of the data frame as some rows have been dropped and the index values are not aligned.

In [258]:
df = df.reset_index()
df.drop('index',axis=1,inplace = True)

In [259]:
df[df['ram'].str.contains('inbuilt')]

brand                      model   price  rating  sim_type   5g volte  \
435   apple           iphone se 3 2022   43900     NaN  Dual Sim  yes   yes   
478  huawei  mate 50 rs porsche design  239999    81.0  Dual Sim   no   yes   
737   apple                iphone se 4   49990    60.0  Dual Sim  yes   yes   

     nfc ir_blaster processor_brand num_cores  processor_speed  \
435  yes         no          bionic         6             3.22   
478  yes        yes      snapdragon         8             3.20   
737  yes         no          bionic         6             3.22   

                ram storage                                  battery  \
435   64 GB inbuilt     NaN                            Not Available   
478  512 GB inbuilt     NaN  4700 mAh Battery with 66W Fast Charging   
737   64 GB inbuilt     NaN                            Not Available   

                                         display    display_type  \
435            4.7 inches, 750 x 1334 px Display  Normal Display   
478  6.74 inches, 1212 x 2616 px, 120 Hz Display  Normal Display   
737            6.1 inches, 750 x 1580 px Display  Normal Display   

                                                camera  \
435                     12 MP Rear & 7 MP Front Camera   
478  50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...   
737                  12 MP Rear & 10.8 MP Front Camera   

                                  card                os  
435          Memory Card Not Supported           iOS v15  
478  Memory Card (Hybrid), upto 256 GB  Hongmeng OS v3.0  
737          Memory Card Not Supported           iOS v16

In [260]:
df.iloc[435,12] = "4 GB RAM"
df.iloc[478,12] = "12 GB RAM"
df.iloc[737,12] = "4 GB RAM"

In [261]:
df['ram'].str.split(" ")[0]

['12\u2009GB', 'RAM']

In [262]:
df['ram'] = df['ram'].str.split("\u2009").str.get(0)

Let's split the imputed values once again, this time using the " " character as a separator.

In [263]:
df['ram'] = df['ram'].str.split(" ").str.get(0)

In [264]:
df['storage'] = df['storage'].str.split(" ").str.get(1).str.split("\u2009").str.get(0)

In [265]:
df.loc[df['storage'] =='1',df.columns[13]] = "1024" #as it's 1 tb not gb

In [266]:
df['storage'].value_counts()

128     523
64      191
256     157
32       67
512      21
16       12
1024      5
8         1
Name: storage, dtype: int64

In [267]:
df['storage'].value_counts()

128     523
64      191
256     157
32       67
512      21
16       12
1024      5
8         1
Name: storage, dtype: int64

In this code, we are converting the datatype of 4 columns in the data frame to integer: 'storage', 'ram', 'num_cores' and 'processor_speed'.

In [295]:
df['storage'] = df['storage'].astype('int')
df['ram'] = df['ram'].astype('int')
df['num_cores'] = df['num_cores'].astype('int')
df['processor_speed'] = df['processor_speed'].astype('int')

In [296]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   brand            980 non-null    object 
 1   model            980 non-null    object 
 2   price            980 non-null    int64  
 3   rating           879 non-null    float64
 4   sim_type         980 non-null    object 
 5   5g               980 non-null    object 
 6   volte            980 non-null    object 
 7   nfc              980 non-null    object 
 8   ir_blaster       980 non-null    object 
 9   processor_brand  980 non-null    object 
 10  num_cores        980 non-null    int32  
 11  processor_speed  980 non-null    int32  
 12  ram              980 non-null    int32  
 13  storage          980 non-null    int32  
 14  battery          980 non-null    object 
 15  display          980 non-null    object 
 16  display_type     980 non-null    object 
 17  camera          

In [311]:
df['battery']

0       5000 mAh Battery with 100W Fast Charging
1        5000 mAh Battery with 33W Fast Charging
2        5000 mAh Battery with 15W Fast Charging
3            5000 mAh Battery with Fast Charging
4        5000 mAh Battery with 67W Fast Charging
5        5000 mAh Battery with 25W Fast Charging
6            3279 mAh Battery with Fast Charging
7       4980 mAh Battery with 120W Fast Charging
8        4500 mAh Battery with 33W Fast Charging
9        4500 mAh Battery with 80W Fast Charging
10       5000 mAh Battery with 33W Fast Charging
11       5000 mAh Battery with 33W Fast Charging
12       5000 mAh Battery with 67W Fast Charging
13       5000 mAh Battery with 18W Fast Charging
14       5000 mAh Battery with 45W Fast Charging
15           3240 mAh Battery with Fast Charging
16       5000 mAh Battery with 10W Fast Charging
17       4700 mAh Battery with 80W Fast Charging
18       5000 mAh Battery with 80W Fast Charging
19       5000 mAh Battery with 18W Fast Charging
20      5000 mAh Bat

Let's extract the information from the "battery" column, which contains information about the battery power, availability of fast charging, and fast charging capacity, and split it into separate columns.

In [304]:
df['battery'][0]

'5000\u2009mAh Battery with 100W Fast Charging'

A function called fast_charging has been defined to identify if a given string x contains the words "Fast Charging". If it does, the function returns 1, otherwise it returns 0.

In [305]:
def fast_charging(x):
    if "Fast Charging" in x:
        return 1
    else:
        return 0

In [309]:
fast_charging = df['battery'].apply(fast_charging)

In [313]:
df.insert(15,'fast_charging',fast_charging)

In [317]:
df['battery'][0]

'5000\u2009mAh Battery with 100W Fast Charging'

Let's create a new column called "fast_charging_capacity" which will contain the fast charging capacity of the device, extracted from the "battery" column. This column will be inserted at the 16th position.

In [344]:
fast_charging_capacity = df['battery'].str.split("with").str.get(1).str.strip().str.split(" ").str.get(0).str.split("W").str.get(0)
df.insert(16,'fast_charging_capacity',fast_charging_capacity)

In [345]:
df['fast_charging_capacity'].replace('Fast',1, inplace=True)

In [346]:
df['fast_charging_capacity'].value_counts()

33      152
18      128
1        68
67       65
25       53
120      46
15       43
80       42
66       37
10       33
30       32
65       30
44       23
45       17
20       10
68        7
100       7
150       7
125       6
22.5      5
40        5
60        4
55        3
21        2
50        2
210       2
240       1
19        1
200       1
135       1
165       1
180       1
27        1
68.2      1
Name: fast_charging_capacity, dtype: int64

In [348]:
df['fast_charging_capacity'] = df['fast_charging_capacity'].astype('float')

In [349]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   brand                   980 non-null    object 
 1   model                   980 non-null    object 
 2   price                   980 non-null    int64  
 3   rating                  980 non-null    float64
 4   sim_type                980 non-null    object 
 5   5g                      980 non-null    object 
 6   volte                   980 non-null    object 
 7   nfc                     980 non-null    object 
 8   ir_blaster              980 non-null    object 
 9   processor_brand         980 non-null    object 
 10  num_cores               980 non-null    int32  
 11  processor_speed         980 non-null    int32  
 12  ram                     980 non-null    int32  
 13  storage                 980 non-null    int32  
 14  battery                 980 non-null    ob

In [353]:
df['battery']=df['battery'].str.split().str.get(0)

In [361]:
df['fast_charging_capacity'].fillna(-1,inplace = True)

In [364]:
df['display'][0]

'6.7 inches, 1440\u2009x\u20093216\u2009px, 120 Hz Display with Punch Hole'

To separate the information present in the "display" column, we will create new columns for screen size, resolution, refresh rate, and display type. The steps for this would involve splitting the information by "," and " ". The values for each of these columns will be extracted and assigned to their respective columns. Finally, we will have 4 separate columns containing the specific details from the "display" column.

In [367]:
screen_size = df['display'].str.split(",").str.get(0)

In [382]:
screen_resolution = df['display'].str.split(" ").str.get(2).str.replace('\u2009','')

In [397]:
df['display'][0]

'6.7 inches, 1440\u2009x\u20093216\u2009px, 120 Hz Display with Punch Hole'

In [412]:
df['display'].str.split("\u2009").str.get(-1).str.split(" ")

0             [px,, 120, Hz, Display, with, Punch, Hole]
1             [px,, 120, Hz, Display, with, Punch, Hole]
2       [px,, 90, Hz, Display, with, Water, Drop, Notch]
3             [px,, 120, Hz, Display, with, Punch, Hole]
4             [px,, 120, Hz, Display, with, Punch, Hole]
5      [px,, 120, Hz, Display, with, Water, Drop, Notch]
6                      [px, Display, with, Small, Notch]
7             [px,, 120, Hz, Display, with, Punch, Hole]
8             [px,, 120, Hz, Display, with, Punch, Hole]
9              [px,, 90, Hz, Display, with, Punch, Hole]
10            [px,, 120, Hz, Display, with, Punch, Hole]
11      [px,, 90, Hz, Display, with, Water, Drop, Notch]
12            [px,, 120, Hz, Display, with, Punch, Hole]
13     [px,, 120, Hz, Display, with, Water, Drop, Notch]
14            [px,, 120, Hz, Display, with, Punch, Hole]
15                     [px, Display, with, Small, Notch]
16               [px, Display, with, Water, Drop, Notch]
17            [px,, 120, Hz, Di

In [403]:
df['display'][0]

'6.7 inches, 1440\u2009x\u20093216\u2009px, 120 Hz Display with Punch Hole'

In [424]:
refresh_rate = df['display'].str.strip().str.split(',').str.get(2).str.strip().str.findall(r'\d{2,3}').str.get(0).apply(lambda x: 60 if pd.isna(x) else x).astype(int)

In [440]:
display_type2 = df['display'].str.strip().str.split('with').str.get(-1).str.strip()

In [441]:
display_type2.loc[display_type2.str.contains("inch")] = "No info available"

In [442]:
display_type2.value_counts()

Punch Hole           533
Water Drop Notch     309
No info available     89
Small Notch           25
Large Notch           18
Dual Punch Hole        6
Name: display, dtype: int64

Below code inserts four new columns into the DataFrame, starting at the 19th position. The columns are named "screen_size", "screen_resolution", "refresh_rate", and "display_category". These columns are being created from the information in the "display" column of the DataFrame.

In [449]:
df.insert(19,'screen_size',screen_size)
df.insert(20,'screen_resolution',screen_resolution)
df.insert(21,'refresh_rate',refresh_rate)
df.insert(22,'display_category',display_type2)

In [451]:
df.drop('display',axis = 1, inplace = True)

In [459]:
df['screen_size'] = df['screen_size'].str.split(" ").str.get(0).astype('float')

In [460]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   brand                   980 non-null    object 
 1   model                   980 non-null    object 
 2   price                   980 non-null    int64  
 3   rating                  980 non-null    float64
 4   sim_type                980 non-null    object 
 5   5g                      980 non-null    object 
 6   volte                   980 non-null    object 
 7   nfc                     980 non-null    object 
 8   ir_blaster              980 non-null    object 
 9   processor_brand         980 non-null    object 
 10  num_cores               980 non-null    int32  
 11  processor_speed         980 non-null    int32  
 12  ram                     980 non-null    int32  
 13  storage                 980 non-null    int32  
 14  battery                 980 non-null    ob

In [466]:
df['camera'].value_counts()

50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                             23
12 MP + 12 MP Dual Rear & 12 MP Front Camera                           20
13 MP Rear & 5 MP Front Camera                                         20
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                    20
50 MP + 2 MP Dual Rear & 8 MP Front Camera                             19
8 MP Rear & 5 MP Front Camera                                          19
64 MP Quad Rear & 32 MP Front Camera                                   18
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  18
13 MP + 2 MP Dual Rear & 8 MP Front Camera                             18
64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   16
50 MP + 2 MP Dual Rear & 5 MP Front Ca

The camera_extractor function takes a text string as an input and returns a string that represents the number of cameras based on the text. If the text contains the word 'Quad', the function returns '4', if the text contains the word 'Triple', the function returns '3', if the text contains the word 'Dual', the function returns '2', if the text contains the word 'Missing', the function returns '0', and if none of the above conditions are met, the function returns '1'.

In [472]:
def camera_extractor(text):
    if 'Quad' in text:
        return '4'
    elif 'Triple' in text:
        return '3'
    elif 'Dual' in text:
        return '2'
    elif 'Missing' in text:
        return '0'
    else:
        return '1'

In [473]:
camera_num = df['camera'].apply(camera_extractor)

In [476]:
num_front_cameras = df['camera'].str.strip().str.split('&').str.get(1).str.strip().fillna('Missing').apply(camera_extractor)

In [478]:
df.insert(23,'num_back_camera',camera_num)
df.insert(24,'num_front_camera',num_front_cameras)

In [479]:
df.drop('camera',axis = 1, inplace= True)

In [488]:
df['card']= df['card'].str.strip()

This code block replaces various string values present in the 'card' column of the dataframe with their respective integer values. The values being replaced are as follows:

'Not Available' is replaced with -1<br>
'Memory Card Supported, upto 1 TB' is replaced with 1024<br>
'Memory Card Not Supported' is replaced with 0<br>
'Memory Card Supported, upto 512 GB' is replaced with 512<br>
'Memory Card (Hybrid), upto 1 TB' is replaced with 1024<br>
'Memory Card Supported, upto 256 GB' is replaced with 256<br>
'Memory Card Supported' is replaced with 1<br>
'Memory Card (Hybrid)' is replaced with 1<br>
'Memory Card (Hybrid), upto 256 GB' is replaced with 256<br>
'Memory Card (Hybrid), upto 512 GB' is replaced with 512<br>
'Memory Card Supported, upto 128 GB' is replaced with 128<br>
'Memory Card Supported, upto 2 TB' is replaced with 2048<br>
'Memory Card (Hybrid), upto 128 GB' is replaced with 128<br>
'Memory Card Supported, upto 32 GB' is replaced with 32<br>
'Memory Card (Hybrid), upto 64 GB' is replaced with 64<br>
'Memory Card (Hybrid), upto 2 TB' is replaced with 2048<br>
'Memory Card Supported, upto 1000 GB' is replaced with 1000<br>
The changes are made in place, meaning the dataframe is directly modified without creating a new dataframe.

In [491]:
df['card'].replace({
    'Not Available': -1,
    'Memory Card Supported, upto 1 TB': 1024,
    'Memory Card Not Supported': 0,
    'Memory Card Supported, upto 512 GB': 512,
    'Memory Card (Hybrid), upto 1 TB': 1024, 
    'Memory Card Supported, upto 256 GB': 256,
    'Memory Card Supported': 1, 
    'Memory Card (Hybrid)': 1,
    'Memory Card (Hybrid), upto 256 GB': 256,
    'Memory Card (Hybrid), upto 512 GB': 512,
    'Memory Card Supported, upto 128 GB': 128,
    'Memory Card Supported, upto 2 TB': 2048, 
    'Memory Card (Hybrid), upto 128 GB': 128,
    'Memory Card Supported, upto 32 GB': 32, 
    'Memory Card (Hybrid), upto 64 GB': 64,
    'Memory Card (Hybrid), upto 2 TB': 2048,
    'Memory Card Supported, upto 1000 GB': 1000
}, inplace=True)

In [492]:
df['card'].value_counts()

 1024    262
-1       225
 0       129
 1       119
 512     116
 256     104
 128      10
 2048      8
 32        3
 64        3
 1000      1
Name: card, dtype: int64

In [516]:
os_version=df['os'].str.strip().str.split(" ").str[1:].str.join(" ")

In [517]:
df['os'] = df['os'].str.strip().str.split(" ").str.get(0)

In [521]:
df.insert(26,'os_version',os_version)

In [522]:
df.head()

brand              model  price  rating  sim_type   5g volte  nfc  \
0   oneplus              11 5g  54999    89.0  Dual Sim  yes   yes  yes   
1   oneplus  nord ce 2 lite 5g  19989    81.0  Dual Sim  yes   yes   no   
2   samsung      galaxy a14 5g  16499    75.0  Dual Sim  yes   yes   no   
3  motorola        moto g62 5g  14999    81.0  Dual Sim  yes   yes   no   
4    realme        10 pro plus  24999    82.0  Dual Sim  yes   yes   no   

  ir_blaster processor_brand  num_cores  processor_speed  ram  storage  \
0         no      snapdragon          8                3   12      256   
1         no      snapdragon          8                2    6      128   
2         no          exynos          8                2    4       64   
3         no      snapdragon          8                2    6      128   
4         no       dimensity          8                2    6      128   

  battery  fast_charging  fast_charging_capacity    display_type  screen_size  \
0    5000              1                   100.0  Normal Display         6.70   
1    5000              1                    33.0  Normal Display         6.59   
2    5000              1                    15.0  Normal Display         6.60   
3    5000              1                     1.0  Normal Display         6.55   
4    5000              1                    67.0  Normal Display         6.70   

  screen_resolution  refresh_rate  display_category num_back_camera  \
0      1440x3216px,           120        Punch Hole               3   
1      1080x2412px,           120        Punch Hole               3   
2      1080x2408px,            90  Water Drop Notch               3   
3      1080x2400px,           120        Punch Hole               3   
4      1080x2412px,           120        Punch Hole               3   

  num_front_camera  card       os os_version  
0                1     0  Android        v13  
1                1  1024  Android        v12  
2                1  1024  Android        v13  
3                1  1024  Android        v12  
4                1     0  Android        v13

In [529]:
df.loc[df['os'].str.contains('Not'),df.columns[24]] = "Not Available"
df.loc[df['os'].str.contains('Not'),df.columns[25]] = "Not Available"

In [523]:
#Finally the data is cleaned. Let's export it

df.to_csv('featured_engeneered_data.csv',index = False)

# One hot encoding

One-Hot Encoding is a technique that converts categorical data into a binary format that can be used in machine learning. It's used when working with categorical data that can't be easily represented numerically, and is often used with decision trees, random forests, and neural networks.

Removing "model" column as it will not add any details into our analysis

In [524]:
df.drop('model',axis=1,inplace  = True)

In [530]:
df.head()

brand  price  rating  sim_type   5g volte  nfc ir_blaster  \
0   oneplus  54999    89.0  Dual Sim  yes   yes  yes         no   
1   oneplus  19989    81.0  Dual Sim  yes   yes   no         no   
2   samsung  16499    75.0  Dual Sim  yes   yes   no         no   
3  motorola  14999    81.0  Dual Sim  yes   yes   no         no   
4    realme  24999    82.0  Dual Sim  yes   yes   no         no   

  processor_brand  num_cores  processor_speed  ram  storage battery  \
0      snapdragon          8                3   12      256    5000   
1      snapdragon          8                2    6      128    5000   
2          exynos          8                2    4       64    5000   
3      snapdragon          8                2    6      128    5000   
4       dimensity          8                2    6      128    5000   

   fast_charging  fast_charging_capacity    display_type  screen_size  \
0              1                   100.0  Normal Display         6.70   
1              1                    33.0  Normal Display         6.59   
2              1                    15.0  Normal Display         6.60   
3              1                     1.0  Normal Display         6.55   
4              1                    67.0  Normal Display         6.70   

  screen_resolution  refresh_rate  display_category num_back_camera  \
0      1440x3216px,           120        Punch Hole               3   
1      1080x2412px,           120        Punch Hole               3   
2      1080x2408px,            90  Water Drop Notch               3   
3      1080x2400px,           120        Punch Hole               3   
4      1080x2412px,           120        Punch Hole               3   

  num_front_camera  card       os os_version  
0                1     0  Android        v13  
1                1  1024  Android        v12  
2                1  1024  Android        v13  
3                1  1024  Android        v12  
4                1     0  Android        v13

This code creates a new DataFrame by performing one-hot encoding on a set of categorical columns in a given DataFrame (df).

The list of columns to encode is defined in the cols variable. The for loop iterates through each column and applies the pd.get_dummies() function to create a new DataFrame with binary columns for each unique value in the original categorical column.

The resulting binary columns are concatenated horizontally using pd.concat() with the argument axis=1 to combine them with the previous set of encoded columns. The resulting DataFrame a contains binary columns for each unique value in the categorical columns in the original DataFrame, which can be used as input to machine learning models that require numerical data.

In [546]:
cols = ['brand','sim_type','5g','volte','nfc','ir_blaster','processor_brand','display_type','display_category','os']
a = pd.DataFrame()
for i in cols:
    a = pd.concat([a,pd.get_dummies(df[i])],axis = 1)
                   

In [549]:
df = pd.concat([df,a],axis = 1)

The data has been processed and prepared in a way that is suitable for input into a regression model. The resulting data is in a format that the regression model can use for making predictions. Let's export this data

In [550]:
df.to_csv("model_ready_data.csv",index=False)